In [49]:
class SamLr:

  def __init__(self):
    self.m = None
    self.b = None

  def fit(self,x_train,y_train):
    num = 0
    den = 0
    for i in range(x_train.shape[0]):
      num = num+((x_train[i] - x_train.mean())*(y_train[i]-y_train.mean()))
      den = den+((x_train[i] - x_train.mean())*(x_train[i] - x_train.mean()))
    self.m = num/den
    self.b=y_train.mean()-(self.m*x_train.mean())
    print(self.m)
    print(self.b)
  def predict(self,x_test):
    return (self.m*x_test) + self.b


In [2]:
import numpy as np
import pandas as pd


In [6]:
df = pd.read_csv("/content/placement.csv",usecols=["cgpa","placement"])

In [7]:
df.head()

cgpa  placement
0   6.8          1
1   5.9          0
2   5.3          0
3   7.4          1
4   5.8          0

In [8]:
x = df.iloc[:,0].values
y = df.iloc[:,1].values

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [18]:
x_train.shape

(80,)

In [50]:
lr = SamLr()

In [51]:
lr.fit(x_train,y_train)

0.34840537149928863
-1.585076453706393


In [22]:
from sklearn.linear_model import LinearRegression

In [24]:
slr = LinearRegression()

In [26]:
x_train_reshaped = np.array(x_train).reshape(-1, 1)
y_train_reshaped = np.array(y_train).reshape(-1, 1)

slr.fit(x_train_reshaped, y_train_reshaped)

LinearRegression()

In [27]:
slr.coef_

array([[0.34840537]])

In [28]:
slr.intercept_

array([-1.58507645])

In [38]:
x_test[0]

7.5

In [52]:
lr.predict(x_test)

array([1.02796383, 1.06280437, 0.54019631, 0.05242879, 0.22663148,
       0.05242879, 0.26147202, 0.50535578, 0.22663148, 0.64471792,
       0.57503685, 0.22663148, 0.12210987, 0.54019631, 0.78408007,
       0.88860168, 0.9931233 , 0.85376115, 0.95828276, 0.67955846])

In [53]:
x_testre = np.array(x_test).reshape(-1,1)
slr.predict(x_testre)

array([[1.02796383],
       [1.06280437],
       [0.54019631],
       [0.05242879],
       [0.22663148],
       [0.05242879],
       [0.26147202],
       [0.50535578],
       [0.22663148],
       [0.64471792],
       [0.57503685],
       [0.22663148],
       [0.12210987],
       [0.54019631],
       [0.78408007],
       [0.88860168],
       [0.9931233 ],
       [0.85376115],
       [0.95828276],
       [0.67955846]])